server:
  port: 8089

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: lb://auth-service
          predicates:
            - Path=/auth/**,/login/**,/user/**,/roles/**,/functions/**,/menu/**,/role-functions/**
        - id: upload-service-route
          uri: lb://upload-service
          predicates:
            - Path=/upload/**
        - id: goods-service-route
          uri: lb://goods-service
          predicates:
            - Path=/spus/**,/skus/**,/brands/**,/category/**,/categories/**,/specGroups/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://www.eshop.com"
            allowed-headers: "*"
            allowed-methods: "*"
            allow-credentials: true

eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:7356/eureka/